name: Pre-Release

on:
  push:
    branches: [main]

jobs:
  prerelease:
    name: Pre-Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    if: github.ref == 'refs/heads/main'
    env:
      PRERELEASE_ID: beta # Change to 'alpha' or other as needed
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@christchurchmayfair'
      - name: Install dependencies
        run: npm ci
      - name: Bump pre-release version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm --no-git-tag-version version prerelease
          git add package.json package-lock.json || true
          git commit -m "ci: bump pre-release version [skip ci]" || echo "No changes to commit"
      - name: Build
        run: npm run build
      - run: git push origin
      - name: Publish pre-release to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --tag next